### PR TITLE
Development has been made to override the relevant phase in child POMs.

### PR DESCRIPTION
**Pull request by omercelikceng**
I want to be able to configure this phase in child POMs in certain cases, so I made this change.

### CODE REVIEW

**Comment by omercelikceng** [comment]
@spencergibb Why hasn't my pull request been merged? I want to configure the Antrun plugin in Spring Cloud Stream, and I need this. Why was it closed without any explanation?

**Comment by spencergibb** [comment]
This repo is typically not one we get many contributions for because it is for only for use with the spring cloud project and you did not mention that in the beginning. Can I ask what you need it for in Spring Cloud Stream?

**Comment by omercelikceng** [comment]
Ok, I am sorry @spencergibb.

I made a development in Spring Cloud Stream that injects the project.version into a class at build time using the Antrun plugin. However, in the spring-cloud-build project, the Antrun plugin is configured with different settings, and the spring-cloud-stream project uses spring-cloud-build as its parent POM. I don't want the phase you specified for the Antrun plugin to execute, so I will set it to none. 

For this reason, I made this development and opened a pull request for this project. Additionally, I am very eager to contribute to open source projects and put in significant effort to do so.

Moreover, I would be delighted if you could merge my commit. 

My development in spring cloud stream : https://github.com/spring-cloud/spring-cloud-stream/commit/a8fb34db0e7c0772ca17f5ed8e5e7510d06a8003

**Comment by spencergibb** [comment]
We had to revert that commit because of failures. https://github.com/spring-cloud/spring-cloud-stream/commit/e14bc1cb51cb4475dfe054b91b7f6ba6a4441be1

I'll work with @sobychacko and @olegz if/when it is reintroduced, we can then revisit this.

**Comment by omercelikceng** [comment]
https://github.com/spring-cloud/spring-cloud-stream/pull/3027#issuecomment-2466833763

As I explained in the link above, the solution to the issue is to set the phases to none.
Yes, the code was reverted because this was the cause of the issue. I made this development to solve the problem. Well, you can do it the way you prefer.

**Pull request closed without merging**
